### PR TITLE
Create 03 Misc/02 Tree Shaking ES6

### LINKED ISSUE #15: Create 03 Misc/02 Tree Shaking ES6

### PR DESCRIPTION
**Pull request by nasdan**
Close #15

### CODE REVIEW

**Comment by brauliodiez** [comment]
Is tree shaking enabled by default in webpack 2? can it be disabled?

**Comment by Foxandxss** [comment]
I haven't seen any way to disable it. As soon as it detects ES2015 modules, it will tree shake them.

**Comment by brauliodiez** [comment]
thanks @Foxandxss goot know it, is something you get for free, but cannot be disabled.

**Comment by nasdan** [comment]
Tree shaking is enable while you are using ES6 modules. By default babel use `commonjs` [see](http://babeljs.io/docs/plugins/preset-env/#optionsmodules).

To enable tree shaking you have to include this configuration:

```
{
  "presets": [
    [
      "env",
      {
        "modules": false,
      },
    ],
  ]
}

```

Otherwise is disabled

**Comment by Foxandxss** [comment]
Apparently if you remove the `modules: false` thing in babel. Treeshaking is gone, but HMR won't work.

**Pull request merged**
