### PR TITLE
#53 Fixes on readmy for sample 01 Styles/04 Handling Images

### PR DESCRIPTION
**Pull request by mlopezperez**
- Corrected and rephrased some points in readme.md
- Run all steps to check everything works fine.

### CODE REVIEW

**Comment by nasdan** [comment]
Nice work!  Before merge, could you resolve conflicts with master? Thanks

**Comment by mlopezperez** [comment]
Sorry!! Didn't notice any conflict with master yesterday, I got a "green
light" about merging when I created the PR last night!

I will review this evening and resolve any conflict.

Thanks for the feedback.

2017-03-21 9:55 GMT+01:00 Nasdan <notifications@github.com>:

**Comment by mlopezperez** [comment]
@Nasdan, conflicts solved!

**Comment by nasdan** [comment]
Thanks @mlopezperez 👍

**Pull request merged**
