### PR TITLE
Example with wepack reload when its configuration changes

### PR DESCRIPTION
**Pull request by adrigardi90**
New **06 Webpack reload** module added to the folder **05 Misc** with an example of hot reload when the webpack configuration changes.

Example with a counter that starts each time the webpack config changes and reload automatically the application

@brauliodiez 
@Nasdan

### CODE REVIEW

**Comment by brauliodiez** [comment]
One thing to start would be to create a new branch called 06_webpack_reload_start there you place your startup project (the one you have copied to start with), then create another branch 06_webpack_reload_implementation where you implement your changes.

By doing this and request a pull from implementation to start we just see the real changes

**Comment by brauliodiez** [comment]
In theory should be only this line of code in the package.json?

```
start:reload": "nodemon --watch webpack.config.js ./node_modules/webpack-dev-server/bin/webpack-dev-server.js",
```

Or I'm missing any additional step?

**Comment by adrigardi90** [comment]
Yes indeed. We only need "start:reload"

Regarding the new branches, I'm gonna try to create them and follow the steps just you said

**Comment by brauliodiez** [comment]
Great,
Then you will raise the PR probably from your report.

Anyway, very smary and good trick, is something that we will use in our daily developments.

**Pull request merged**
