### PR TITLE
Import Materialize sample

### PR DESCRIPTION
**Pull request by fjcalzado**
Hi Dani, I've generated a new sample to import Materialize as Braulio suggested. There is no issue for this, create it and assign it to me if you consider so.

### CODE REVIEW

**Comment by brauliodiez** [comment]
Great stuff, this is something you can present on Fridays master session

**Comment by nasdan** [comment]
Great work @fjcalzado, I think it's better to create this sample as `01 Styles/05 Import materialize` because there is a lot of references to 03 SASS and it could be cause too much errors.

**Comment by fjcalzado** [comment]
Ok, I will roll back my changes and leave it as 05

**Comment by fjcalzado** [comment]
I didn't want to mix code so I did everything in a new branch and thus, I will open a new PR. You can reject this one.

**Pull request closed without merging**
