### PR TITLE
updated readme and babelrc to version 7

### PR DESCRIPTION
**Pull request by brauliodiez**

### CODE REVIEW

**Comment by fjcalzado** [comment]
The whole point for setting `useBuiltIns` to `entry` in our `@babel/preset-env` is to allow a plugin to replace the statement `import "@babel/polyfill"` with custom individual imports based on your environment. So, we should have an import of the babel polyfill anywhere, or if we don't need the runtime polyfills, just remove the `useBuiltIns` option. 

In case we do need the polyfills, they are missing, so please do:
```
npm install @babel/polyfill --save
```` 
and create a single file that contains the import statement:
```
import "@babel/polyfill";
```
(add this entry file to webpack entry point, or import this file from your main, but be careful it is imported only once).

**Comment by nasdan** [comment]
The best place to do that is in webpack config `entry` point

**Comment by nasdan** [comment]
I think now it's not needed to import it on webpack config or some where.

But for that, we have to set `useBuiltIns` option to `usage`:

> If we weren't using the env preset with the "useBuiltIns" option set to "usage" we would've had to require the full polyfill only once in our entry point before any other code.

[Babel docs](https://babeljs.io/docs/en/usage#polyfill)

**Comment by nasdan** [comment]
More [docs](https://babeljs.io/docs/en/babel-preset-env#usebuiltins)

**Comment by fjcalzado** [comment]
Definitely, that is my preferred option. With `useBuiltIns` to `usage` we also optimize bundle size, as the `preset-env` will only import the needed polyfill in each file, instead of including the whole polyfill package. 

@brauliodiez  is there any reason why you set `useBuiltIns` to `entry`? If not, try setting it to `usage`  as @Nasdan mentioned (and just install the polyfills, no need to import)

**Pull request merged**
